name: elki_app
description: Elki test project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  equatable: ^2.0.3
  bloc_concurrency: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  analyzer: ^4.2.0

flutter:
  uses-material-design: true
